### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by TT-IPIP** [C4illin/ASFclaim#5]
```
import http from 'node:http';
       ^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/ASFclaim/index.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

**Comment by C4illin** [comment]
It should be fixed now, try again with the latest version

**Comment by TT-IPIP** [comment]
```
import fetch from "node-fetch"
       ^^^^^

SyntaxError: Unexpected identifier

**Comment by C4illin** [comment]
What node version do you have?

**Comment by C4illin** [comment]
Reopen if updating node didn't fix it!
